// front/src/components/NaverMap.tsx
import { useState, useEffect } from 'react';
import Card from '@mui/material/Card';

function NaverMap() {
  const container: string = 'map';
  const { naver } = window;
  const tm128 = new naver.maps.Point(314213, 545289); // mapx, mapy
  const latLng = naver.maps.TransCoord.fromTM128ToLatLng(tm128);
  const mapOptions = {
    // center: new naver.maps.LatLng(37.3595704, 127.105399),
    center: latLng,
    zoom: 20,
  };

  useEffect(() => {
    const map = new naver.maps.Map(container, mapOptions);
  }, []);

  return (
    <>
      <Card>
        <div id={container} style={{ width: '100%', height: '90vh' }} />
      </Card>
    </>
  );
}

export default NaverMap;

// front/src/lib/NaverMap.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import Card from '@smui/card';

  export let style: string = '';

  let map: naver.maps.Map;

  function initMap() {
    const { naver } = window;
    const mapOptions = {
      center: new naver.maps.LatLng(37.5642135, 127.0016985),
      zoom: 12,
    };
    map = new naver.maps.Map('map', mapOptions);
  }

  onMount(() => {
    initMap();
  });
</script>

<svelte:head>
  <script
    lang="javascript"
    src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=4frzvj451g&submodules=geocoder"></script>
</svelte:head>

<Card {style}>
  <div id="map" style="width:100%;height:100%;" />
</Card>
